branch-defaults:
  default:
    environment: file-staging
    group_suffix: null
global:
  application_name: talkinnovations-staging
  branch: null
  default_ec2_keyname: tic-ec2
  default_platform: Docker running on 64bit Amazon Linux 2
  default_region: ap-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
